name: llam_local
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  aub_ai: ^1.0.3
  change_app_package_name: ^1.2.0
  connectivity_plus: ^6.0.3
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_secure_storage: ^9.2.2
  google_fonts: ^6.2.1
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  open_file: ^3.3.2
  path: ^1.9.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  pretty_dio_logger: ^1.3.1
  url_launcher: ^6.3.0
  widget_and_text_animator: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  
  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon.png"
